"use client";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { CheckCircle2, CreditCard, LoaderCircle, ShieldCheck } from "lucide-react";
import AppShell from "@/app/components/navigation/AppShell";
type Bank = { code: string; name: string }; type Profile = { bank_name: string; account_name: string; account_last4: string };
export default function ProjectPaymentPage() {
  const [profile, setProfile] = useState<Profile | null>(null); const [banks, setBanks] = useState<Bank[]>([]); const [ready, setReady] = useState(false); const [busy, setBusy] = useState(true); const [error, setError] = useState("");
  useEffect(() => { Promise.all([fetch("/api/projects/payments/profile", { cache: "no-store" }).then((r) => r.json()), fetch("/api/projects/payments/banks", { cache: "no-store" }).then(async (r) => ({ ok: r.ok, data: await r.json() }))]).then(([profileData, bankData]) => { setProfile(profileData.profile ?? null); setReady(Boolean(profileData.readiness?.enabled && profileData.readiness?.configured)); if (bankData.ok) setBanks(bankData.data.banks ?? []); else if (bankData.data?.error) setError(bankData.data.error); }).catch(() => setError("Payment setup is temporarily unavailable.")).finally(() => setBusy(false)); }, []);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const form = new FormData(event.currentTarget); const bankCode = String(form.get("bankCode")); const bankName = banks.find((bank) => bank.code === bankCode)?.name ?? ""; try { const response = await fetch("/api/projects/payments/profile", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ bankCode, bankName, accountNumber: form.get("accountNumber") }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Could not verify this account."); setProfile(result.profile); } catch (caught) { setError(caught instanceof Error ? caught.message : "Could not verify this account."); } finally { setBusy(false); } }
  return <AppShell><main className="min-h-screen bg-gradient-to-br from-[#020617] via-[#08111f] to-[#0f172a] px-5 py-8 text-white"><div className="mx-auto max-w-2xl"><Link href="/projects/my" className="text-sm text-cyan-300">← My Projects</Link><div className="mt-5 rounded-3xl border border-white/10 bg-white/[0.03] p-6 sm:p-8"><div className="flex items-start gap-4"><div className="rounded-2xl bg-cyan-300/10 p-3 text-cyan-300"><CreditCard /></div><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-cyan-300">Reward payments</p><h1 className="mt-1 text-2xl font-bold">Your payout account</h1><p className="mt-2 text-sm leading-6 text-slate-400">Verify a Nigerian bank account for eligible Project rewards. ASCEND stores a Flutterwave beneficiary reference and only the last four digits—not your complete account number.</p></div></div>{!ready && !busy && <div className="mt-6 rounded-2xl border border-amber-300/15 bg-amber-300/[0.06] p-4 text-sm text-amber-100">Reward payments are not enabled yet.</div>}{profile && <div className="mt-6 rounded-2xl border border-emerald-300/15 bg-emerald-300/[0.05] p-5"><p className="flex items-center gap-2 font-semibold text-emerald-200"><CheckCircle2 size={18} />Verified payout account</p><p className="mt-3 text-lg font-semibold">{profile.account_name}</p><p className="mt-1 text-sm text-slate-400">{profile.bank_name} · ••••••{profile.account_last4}</p></div>}{error && <p className="mt-5 rounded-xl border border-rose-300/15 p-3 text-sm text-rose-200">{error}</p>}<form onSubmit={save} className="mt-6 space-y-4"><select name="bankCode" required disabled={!ready || busy} className="w-full rounded-xl border border-white/10 bg-[#0a1320] p-3 text-sm"><option value="">Choose your bank</option>{banks.map((bank) => <option key={bank.code} value={bank.code}>{bank.name}</option>)}</select><input name="accountNumber" inputMode="numeric" pattern="[0-9]{10}" maxLength={10} required disabled={!ready || busy} placeholder="10-digit account number" className="w-full rounded-xl border border-white/10 bg-black/20 p-3 text-sm"/><button disabled={!ready || busy} className="flex w-full items-center justify-center gap-2 rounded-xl bg-cyan-500 p-3 font-bold text-slate-950 disabled:opacity-50">{busy ? <LoaderCircle size={17} className="animate-spin"/> : <ShieldCheck size={17}/>}Verify account</button></form></div></div></main></AppShell>;
}
