/* eslint-disable react-hooks/set-state-in-effect */
"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
type Delivery = { id: string; user_id: string; amount_minor: number | null; currency: string | null; benefit_description: string | null; status: string; provider_transfer_id: string | null };
export default function PayoutConsole() {
  const [items, setItems] = useState<Delivery[]>([]); const [error, setError] = useState(""); const [busy, setBusy] = useState("");
  const load = useCallback(async () => { const response = await fetch("/api/projects/admin/projects", { cache: "no-store" }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setItems(result.deliveries ?? []); }, []);
  useEffect(() => { void load().catch((caught) => setError(caught.message)); }, [load]);
  async function act(id: string, action: "initiate" | "reconcile") { if (action === "initiate" && !confirm("Initiate this payout using the verified reward amount and payout account?")) return; setBusy(id + action); setError(""); try { const response = await fetch("/api/projects/admin/payouts", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ deliveryId: id, action }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Payout action failed."); } finally { setBusy(""); } }
  return <main className="min-h-screen bg-[#050a12] px-5 py-8 text-white"><div className="mx-auto max-w-5xl"><Link href="/projects/admin" className="text-sm text-cyan-300">← Projects Admin</Link><h1 className="mt-5 text-3xl font-bold">Reward payouts</h1><p className="mt-2 text-sm text-slate-400">Admin-only payout initiation and provider status reconciliation.</p>{error && <p className="mt-5 rounded-xl border border-rose-300/15 p-3 text-sm text-rose-200">{error}</p>}<div className="mt-6 grid gap-3 md:grid-cols-2">{items.length ? items.map((item) => <article key={item.id} className="rounded-2xl border border-white/10 bg-white/[0.03] p-5"><p className="text-xs uppercase tracking-wider text-violet-200">{item.status.replaceAll("_", " ")}</p><p className="mt-2 text-lg font-semibold">{item.amount_minor ? `${item.currency} ${(item.amount_minor / 100).toLocaleString()}` : item.benefit_description}</p><p className="mt-1 text-xs text-slate-500">Participant {item.user_id}</p><div className="mt-4 flex gap-2">{!item.provider_transfer_id && item.amount_minor && <button disabled={Boolean(busy)} onClick={() => act(item.id, "initiate")} className="rounded-lg bg-violet-400 px-3 py-2 text-xs font-bold text-slate-950">Initiate payout</button>}{item.provider_transfer_id && item.status !== "delivered" && <button disabled={Boolean(busy)} onClick={() => act(item.id, "reconcile")} className="rounded-lg border border-white/10 px-3 py-2 text-xs">Verify status</button>}</div></article>) : <p className="rounded-xl border border-dashed border-white/10 p-6 text-sm text-slate-500">No reward payouts are waiting.</p>}</div></div></main>;
}
