"use client";
import { FormEvent, useCallback, useEffect, useRef, useState } from "react";
import Link from "next/link";
import { LoaderCircle, RefreshCw, Save, ShieldCheck } from "lucide-react";

type AdminData={projects:Array<{id:string;title:string;project_type:string;category:string;status:string;submission_deadline:string;experience_kind:string}>;submissions:Array<{id:string;project_id:string;user_id:string;status:string;current_version:number;submitted_at:string|null;participant_note:string;deliverable_responses:Record<string,string>}>};
export default function ProjectsAdminConsole(){const[data,setData]=useState<AdminData|null>(null);const[error,setError]=useState("");const[busy,setBusy]=useState("");const[experienceKind,setExperienceKind]=useState("build");const[message,setMessage]=useState("");const requestLock=useRef(false);
 const load=useCallback(async()=>{if(requestLock.current)return;requestLock.current=true;setError("");setBusy("load");try{const response=await fetch("/api/projects/admin/projects",{cache:"no-store"});const result=await response.json();if(!response.ok)throw new Error(result.error||"Unable to load Projects admin.");setData(result);}catch(caught){setError(caught instanceof Error?caught.message:"Unable to load Projects admin.");}finally{requestLock.current=false;setBusy("")}},[]);useEffect(()=>{
  // Loading remote admin state is the synchronization performed by this effect.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  void load()
 },[load]);
 async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();if(requestLock.current)return;requestLock.current=true;setBusy("create");setError("");const formElement=event.currentTarget;const form=new FormData(formElement);try{const payload={experienceKind,title:form.get("title"),summary:form.get("summary"),brief:form.get("brief"),category:form.get("category"),difficulty:form.get("difficulty"),estimatedMinutes:Number(form.get("estimatedMinutes")),submissionDeadline:new Date(String(form.get("submissionDeadline"))).toISOString(),skills:String(form.get("skills")||"").split(","),deliverables:String(form.get("deliverables")||"").split("\n")};const response=await fetch("/api/projects/admin/projects",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok)throw new Error(result.error||"Could not create draft.");formElement.reset();requestLock.current=false;await load();}catch(caught){setError(caught instanceof Error?caught.message:"Could not create draft.");}finally{requestLock.current=false;setBusy("")}}
 async function transition(projectId:string,status:string){
  if(requestLock.current)return;
  requestLock.current=true;setBusy(projectId+status);setError("");setMessage("");
  try{
   const response=await fetch("/api/projects/admin/projects",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({projectId,status})});
   const result=await response.json();if(!response.ok)throw new Error(result.error||"Could not update Project.");
   if(!result.project || result.project.id!==projectId || result.project.status!==status)throw new Error("The update could not be confirmed. Refresh to check its status before retrying.");
   setData(current=>current?{...current,projects:current.projects.map(project=>project.id===projectId?{...project,...result.project}:project)}:current);
   setMessage(`${result.project.title} — ${status==="review"?"ready to publish":status.replaceAll("_"," ")}.`);
  }catch(caught){setError(caught instanceof Error?caught.message:"Could not update Project. Refresh to check its status.");}
  finally{requestLock.current=false;setBusy("");}
 }
 async function review(submissionId:string,outcome:string){if(requestLock.current)return;const feedback=window.prompt(outcome==="revision_requested"?"Explain the required revision:":"Add feedback for the participant:","");if(feedback===null)return;const scoreText=outcome==="not_completed"?"":window.prompt("Overall score from 0 to 100 (optional):","");requestLock.current=true;setError("");setBusy(submissionId);try{const response=await fetch("/api/projects/admin/reviews",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({submissionId,outcome,userFeedback:feedback,overallScore:scoreText?Number(scoreText):null})});const result=await response.json();if(!response.ok)throw new Error(result.error||"Could not review submission.");setData(current=>current?{...current,submissions:current.submissions.filter(item=>item.id!==submissionId)}:current);setMessage("Review saved.");}catch(caught){setError(caught instanceof Error?caught.message:"Could not review submission.");}finally{requestLock.current=false;setBusy("")}}
 if(!data&&busy==="load")return <div className="flex min-h-screen items-center justify-center bg-[#050a12] text-slate-300"><LoaderCircle className="mr-2 animate-spin"/>Loading Projects admin…</div>;
 return <main className="min-h-screen bg-[#050a12] px-5 py-8 text-white [&_button:disabled]:cursor-wait [&_button:disabled]:opacity-50"><div className="mx-auto max-w-7xl"><div className="flex items-start justify-between gap-4"><div><p className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.18em] text-cyan-300"><ShieldCheck size={16}/>Private operations</p><h1 className="mt-2 text-3xl font-bold">Projects Admin</h1><p className="mt-2 text-sm text-slate-400">Manage your projects and give students useful feedback.</p></div><div className="flex gap-2"><Link href="/projects" className="rounded-xl border border-white/10 px-4 py-2 text-sm">User view</Link><button disabled={Boolean(busy)} aria-label="Refresh projects" onClick={()=>void load()} className="rounded-xl border border-white/10 p-2"><RefreshCw size={17} className={busy==="load"?"animate-spin":""}/></button></div></div>{error&&<p className="mt-4 rounded-xl border border-rose-300/15 bg-rose-300/[0.06] p-3 text-sm text-rose-200" role="alert">{error}</p>}{message&&<p role="status" className="mt-4 text-sm text-emerald-200">{message}</p>}
 <section className="mt-7 space-y-6"><details className="rounded-2xl border border-white/10 bg-white/[0.02]"><summary className="cursor-pointer px-5 py-4 text-sm font-semibold text-cyan-200">Create a project</summary><form onSubmit={create} className="rounded-2xl border border-white/10 bg-white/[0.03] p-5"><h2 className="font-semibold">Create Project draft</h2><label className="mt-4 block text-xs text-slate-400">Experience<select value={experienceKind} onChange={event=>setExperienceKind(event.target.value)} className="mt-1 w-full rounded-xl border border-white/10 bg-[#0a1320] p-3 text-sm"><option value="build">Build a portfolio piece</option><option value="explore">Explore a pathway</option></select></label><div className="mt-4 space-y-3">{[["title","Title"],["summary","Summary"],["category","Category"],["skills","Skills, comma separated"]].map(([name,label])=><label key={name} className="block text-xs text-slate-400">{label}<input required name={name} className="mt-1 w-full rounded-xl border border-white/10 bg-black/20 p-3 text-sm text-white"/></label>)}<label className="block text-xs text-slate-400">Brief<textarea required name="brief" rows={5} className="mt-1 w-full rounded-xl border border-white/10 bg-black/20 p-3 text-sm text-white"/></label><label className="block text-xs text-slate-400">Milestones / deliverables, one per line (max 120 characters each)<textarea required name="deliverables" rows={4} className="mt-1 w-full rounded-xl border border-white/10 bg-black/20 p-3 text-sm text-white"/></label><div className="grid grid-cols-2 gap-2"><select name="difficulty" className="rounded-xl border border-white/10 bg-[#0a1320] p-3 text-sm"><option value="beginner">Beginner</option><option value="intermediate">Intermediate</option><option value="advanced">Advanced</option></select><input name="estimatedMinutes" type="number" min="15" defaultValue="180" className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"/></div><label className="block text-xs text-slate-400">Submission deadline<input required name="submissionDeadline" type="datetime-local" className="mt-1 w-full rounded-xl border border-white/10 bg-black/20 p-3 text-sm"/></label></div><button disabled={Boolean(busy)} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-cyan-500 p-3 text-sm font-bold text-slate-950">{busy==="create"?<LoaderCircle size={16} className="animate-spin"/>:<Save size={16}/>} {busy==="create"?"Creating…":"Create draft"}</button></form></details>
 <div><h2 className="font-semibold">Your projects <span className="ml-2 text-sm font-normal text-slate-400">{data?.projects.length??0}</span></h2><div className="mt-3 space-y-2">{data?.projects.map(project=><div key={project.id} className="rounded-xl border border-white/[0.08] bg-white/[0.025] p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-semibold">{project.title}</p><p className="mt-1 text-xs text-slate-500">{project.category} <span className="ml-2 inline-block rounded-full border border-white/10 px-2 py-0.5 text-slate-300">{project.status==="review"?"Ready to publish":project.status.replaceAll("_"," ")}</span></p></div><div aria-busy={busy.startsWith(project.id)} className="flex flex-wrap gap-2">{project.status==="draft"&&<button disabled={Boolean(busy)} onClick={()=>transition(project.id,"review")} className="rounded-lg border border-white/10 px-3 py-1.5 text-xs">{busy===project.id+"review"?"Sending…":"Send to review"}</button>}{project.status==="review"&&<button disabled={Boolean(busy)} onClick={()=>transition(project.id,"published")} className="rounded-lg bg-emerald-500 px-3 py-1.5 text-xs font-bold text-slate-950">{busy===project.id+"published"?"Publishing…":"Publish"}</button>}{project.status==="published"&&<><button disabled={Boolean(busy)} onClick={()=>transition(project.id,"paused")} className="rounded-lg border border-white/10 px-3 py-1.5 text-xs">{busy===project.id+"paused"?"Pausing…":"Pause"}</button><button disabled={Boolean(busy)} onClick={()=>transition(project.id,"submissions_closed")} className="rounded-lg border border-white/10 px-3 py-1.5 text-xs">{busy===project.id+"submissions_closed"?"Closing…":"Close submissions"}</button></>}{project.status==="paused"&&<button disabled={Boolean(busy)} onClick={()=>transition(project.id,"published")} className="rounded-lg border border-white/10 px-3 py-1.5 text-xs">{busy===project.id+"published"?"Resuming…":"Resume"}</button>}{project.status==="submissions_closed"&&<button disabled={Boolean(busy)} onClick={()=>transition(project.id,"reviewing")} className="rounded-lg border border-white/10 px-3 py-1.5 text-xs">{busy===project.id+"reviewing"?"Updating…":"Begin review"}</button>}{project.status==="reviewing"&&<button disabled={Boolean(busy)} onClick={()=>transition(project.id,"results_ready")} className="rounded-lg border border-white/10 px-3 py-1.5 text-xs">{busy===project.id+"results_ready"?"Updating…":"Results ready"}</button>}{project.status==="results_ready"&&<button disabled={Boolean(busy)} onClick={()=>transition(project.id,"completed")} className="rounded-lg border border-white/10 px-3 py-1.5 text-xs">{busy===project.id+"completed"?"Completing…":"Complete Project"}</button>}</div></div></div>)}</div></div></section>
 <section className="mt-8"><h2 className="font-semibold">Submissions awaiting review</h2><div className="mt-3 grid gap-3">{data?.submissions.length?data.submissions.map(submission=>{const project=data.projects.find(item=>item.id===submission.project_id);return <article key={submission.id} className="rounded-2xl border border-white/10 bg-white/[0.03] p-5"><p className="text-xs text-slate-500">{project?.title??"Project"} · User {submission.user_id} · Version {submission.current_version}</p><div className="mt-3 space-y-2">{Object.entries(submission.deliverable_responses).map(([key,value])=><div key={key} className="rounded-xl bg-black/20 p-3"><p className="text-xs font-semibold text-cyan-300">{key}</p><p className="mt-1 whitespace-pre-wrap text-sm text-slate-300">{value}</p></div>)}</div>{submission.participant_note&&<p className="mt-3 text-sm text-slate-400">Note: {submission.participant_note}</p>}<div className="mt-4 flex flex-wrap gap-2"><button disabled={Boolean(busy)} onClick={()=>review(submission.id,"completed")} className="rounded-lg bg-emerald-500 px-3 py-2 text-xs font-bold text-slate-950">Complete</button><button disabled={Boolean(busy)} onClick={()=>review(submission.id,"revision_requested")} className="rounded-lg bg-amber-400 px-3 py-2 text-xs font-bold text-slate-950">Request revision</button><button disabled={Boolean(busy)} onClick={()=>review(submission.id,"not_completed")} className="rounded-lg border border-rose-300/20 px-3 py-2 text-xs text-rose-200">Not completed</button></div></article>}):<p className="rounded-xl border border-dashed border-white/10 p-6 text-sm text-slate-500">No submissions are waiting for review.</p>}</div></section></div></main>}
