"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { LoaderCircle, RefreshCw, Save, ShieldCheck } from "lucide-react";

type AdminData={projects:Array<{id:string;title:string;project_type:string;category:string;status:string;submission_deadline:string}>;submissions:Array<{id:string;project_id:string;user_id:string;status:string;current_version:number;submitted_at:string|null;participant_note:string;deliverable_responses:Record<string,string>}>};
export default function ProjectsAdminConsole(){const[data,setData]=useState<AdminData|null>(null);const[error,setError]=useState("");const[busy,setBusy]=useState("");
 const load=useCallback(async()=>{setBusy("load");try{const response=await fetch("/api/projects/admin/projects",{cache:"no-store"});const result=await response.json();if(!response.ok)throw new Error(result.error||"Unable to load Projects admin.");setData(result);}catch(caught){setError(caught instanceof Error?caught.message:"Unable to load Projects admin.");}finally{setBusy("")}},[]);useEffect(()=>{
  // Loading remote admin state is the synchronization performed by this effect.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  void load()
 },[load]);
 async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy("create");setError("");const form=new FormData(event.currentTarget);const payload={title:form.get("title"),summary:form.get("summary"),brief:form.get("brief"),category:form.get("category"),difficulty:form.get("difficulty"),estimatedMinutes:Number(form.get("estimatedMinutes")),submissionDeadline:form.get("submissionDeadline"),skills:String(form.get("skills")||"").split(","),deliverables:String(form.get("deliverables")||"").split("\n")};try{const response=await fetch("/api/projects/admin/projects",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok)throw new Error(result.error||"Could not create draft.");event.currentTarget.reset();await load();}catch(caught){setError(caught instanceof Error?caught.message:"Could not create draft.");}finally{setBusy("")}}
 async function transition(projectId:string,status:string){setBusy(projectId+status);setError("");try{const response=await fetch("/api/projects/admin/projects",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({projectId,status})});const result=await response.json();if(!response.ok)throw new Error(result.error||"Could not update Project.");await load();}catch(caught){setError(caught instanceof Error?caught.message:"Could not update Project.");}finally{setBusy("")}}
 async function review(submissionId:string,outcome:string){const feedback=window.prompt(outcome==="revision_requested"?"Explain the required revision:":"Add feedback for the participant:","");if(feedback===null)return;const scoreText=outcome==="not_completed"?"":window.prompt("Overall score from 0 to 100 (optional):","");setBusy(submissionId);try{const response=await fetch("/api/projects/admin/reviews",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({submissionId,outcome,userFeedback:feedback,overallScore:scoreText?Number(scoreText):null})});const result=await response.json();if(!response.ok)throw new Error(result.error||"Could not review submission.");await load();}catch(caught){setError(caught instanceof Error?caught.message:"Could not review submission.");}finally{setBusy("")}}
 if(!data&&busy==="load")return <div className="flex min-h-screen items-center justify-center bg-[#050a12] text-slate-300"><LoaderCircle className="mr-2 animate-spin"/>Loading Projects admin…</div>;
 return <main className="min-h-screen bg-[#050a12] px-5 py-8 text-white"><div className="mx-auto max-w-7xl"><div className="flex items-start justify-between gap-4"><div><p className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.18em] text-cyan-300"><ShieldCheck size={16}/>Private operations</p><h1 className="mt-2 text-3xl font-bold">Projects Admin</h1><p className="mt-2 text-sm text-slate-400">Create controlled drafts, manage lifecycle and review submitted work.</p></div><div className="flex gap-2"><Link href="/projects" className="rounded-xl border border-white/10 px-4 py-2 text-sm">User view</Link><button onClick={()=>void load()} className="rounded-xl border border-white/10 p-2"><RefreshCw size={17}/></button></div></div>{error&&<p className="mt-4 rounded-xl border border-rose-300/15 bg-rose-300/[0.06] p-3 text-sm text-rose-200">{error}</p>}
 <section className="mt-7 grid gap-5 lg:grid-cols-[380px_1fr]"><form onSubmit={create} className="rounded-2xl border border-white/10 bg-white/[0.03] p-5"><h2 className="font-semibold">Create Practice Project draft</h2><div className="mt-4 space-y-3">{[["title","Title"],["summary","Summary"],["category","Category"],["skills","Skills, comma separated"]].map(([name,label])=><label key={name} className="block text-xs text-slate-400">{label}<input required name={name} className="mt-1 w-full rounded-xl border border-white/10 bg-black/20 p-3 text-sm text-white"/></label>)}<label className="block text-xs text-slate-400">Brief<textarea required name="brief" rows={5} className="mt-1 w-full rounded-xl border border-white/10 bg-black/20 p-3 text-sm text-white"/></label><label className="block text-xs text-slate-400">Deliverables, one per line<textarea required name="deliverables" rows={4} className="mt-1 w-full rounded-xl border border-white/10 bg-black/20 p-3 text-sm text-white"/></label><div className="grid grid-cols-2 gap-2"><select name="difficulty" className="rounded-xl border border-white/10 bg-[#0a1320] p-3 text-sm"><option value="beginner">Beginner</option><option value="intermediate">Intermediate</option><option value="advanced">Advanced</option></select><input name="estimatedMinutes" type="number" min="15" defaultValue="180" className="rounded-xl border border-white/10 bg-black/20 p-3 text-sm"/></div><label className="block text-xs text-slate-400">Submission deadline<input required name="submissionDeadline" type="datetime-local" className="mt-1 w-full rounded-xl border border-white/10 bg-black/20 p-3 text-sm"/></label></div><button disabled={busy==="create"} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-cyan-500 p-3 text-sm font-bold text-slate-950"><Save size={16}/>Create controlled draft</button></form>
 <div><h2 className="font-semibold">Project lifecycle</h2><div className="mt-3 space-y-2">{data?.projects.map(project=><div key={project.id} className="rounded-xl border border-white/[0.08] bg-white/[0.025] p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-semibold">{project.title}</p><p className="mt-1 text-xs text-slate-500">{project.category} · {project.status.replaceAll("_"," ")}</p></div><div className="flex flex-wrap gap-2">{project.status==="draft"&&<button onClick={()=>transition(project.id,"review")} className="rounded-lg border border-white/10 px-3 py-1.5 text-xs">Send to review</button>}{project.status==="review"&&<button onClick={()=>transition(project.id,"published")} className="rounded-lg bg-emerald-500 px-3 py-1.5 text-xs font-bold text-slate-950">Publish</button>}{project.status==="published"&&<><button onClick={()=>transition(project.id,"paused")} className="rounded-lg border border-white/10 px-3 py-1.5 text-xs">Pause</button><button onClick={()=>transition(project.id,"submissions_closed")} className="rounded-lg border border-white/10 px-3 py-1.5 text-xs">Close submissions</button></>}{project.status==="paused"&&<button onClick={()=>transition(project.id,"published")} className="rounded-lg border border-white/10 px-3 py-1.5 text-xs">Resume</button>}{project.status==="submissions_closed"&&<button onClick={()=>transition(project.id,"reviewing")} className="rounded-lg border border-white/10 px-3 py-1.5 text-xs">Begin review</button>}{project.status==="reviewing"&&<button onClick={()=>transition(project.id,"results_ready")} className="rounded-lg border border-white/10 px-3 py-1.5 text-xs">Results ready</button>}{project.status==="results_ready"&&<button onClick={()=>transition(project.id,"completed")} className="rounded-lg border border-white/10 px-3 py-1.5 text-xs">Complete Project</button>}</div></div></div>)}</div></div></section>
 <section className="mt-8"><h2 className="font-semibold">Submissions awaiting review</h2><div className="mt-3 grid gap-3">{data?.submissions.length?data.submissions.map(submission=>{const project=data.projects.find(item=>item.id===submission.project_id);return <article key={submission.id} className="rounded-2xl border border-white/10 bg-white/[0.03] p-5"><p className="text-xs text-slate-500">{project?.title??"Project"} · User {submission.user_id} · Version {submission.current_version}</p><div className="mt-3 space-y-2">{Object.entries(submission.deliverable_responses).map(([key,value])=><div key={key} className="rounded-xl bg-black/20 p-3"><p className="text-xs font-semibold text-cyan-300">{key}</p><p className="mt-1 whitespace-pre-wrap text-sm text-slate-300">{value}</p></div>)}</div>{submission.participant_note&&<p className="mt-3 text-sm text-slate-400">Note: {submission.participant_note}</p>}<div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>review(submission.id,"completed")} className="rounded-lg bg-emerald-500 px-3 py-2 text-xs font-bold text-slate-950">Complete</button>{project?.project_type==="reward"&&<button onClick={()=>review(submission.id,"award_recommended")} className="rounded-lg bg-violet-400 px-3 py-2 text-xs font-bold text-slate-950">Confirm award</button>}<button onClick={()=>review(submission.id,"revision_requested")} className="rounded-lg bg-amber-400 px-3 py-2 text-xs font-bold text-slate-950">Request revision</button><button onClick={()=>review(submission.id,"not_completed")} className="rounded-lg border border-rose-300/20 px-3 py-2 text-xs text-rose-200">Not completed</button></div></article>}):<p className="rounded-xl border border-dashed border-white/10 p-6 text-sm text-slate-500">No submissions are waiting for review.</p>}</div></section></div></main>}
