import { NextResponse } from "next/server";
import { z } from "zod";
import { requireAscendWorkAdmin } from "@/lib/ascend-work/admin-auth";
import { archiveLegacyScoutSignals, listScoutSignals, promoteScoutSignal, runPartnerScout, updateScoutSignal } from "@/lib/ascend-work/partner-scout";

export const maxDuration = 60;

const patchSchema = z.discriminatedUnion("action", [
  z.object({ action: z.literal("status"), id: z.string().uuid(), status: z.enum(["new", "reviewing", "dismissed"]) }),
  z.object({ action: z.literal("promote"), id: z.string().uuid(), contactName: z.string().trim().min(2).max(140), contactEmail: z.string().trim().email().max(320), contactRole: z.string().trim().max(140).optional() }),
  z.object({ action: z.literal("archiveLegacy") }),
]);
export async function GET() { try { await requireAscendWorkAdmin(); return NextResponse.json({ signals: await listScoutSignals(), configured: Boolean(process.env.TAVILY_API_KEY) }); } catch (error) { const message = error instanceof Error ? error.message : ""; return NextResponse.json({ error: message.includes("UNAUTHENTICATED") || message.includes("FORBIDDEN") ? "Unauthorized" : "Scout signals could not be loaded." }, { status: message.includes("UNAUTHENTICATED") ? 401 : message.includes("FORBIDDEN") ? 403 : 500 }); } }
export async function POST() { try { await requireAscendWorkAdmin(); return NextResponse.json({ success: true, run: await runPartnerScout("admin") }); } catch (error) { const message = error instanceof Error ? error.message : ""; const providerMissing = message === "SCOUT_PROVIDER_NOT_CONFIGURED"; const alreadyRunning = message === "SCOUT_RUN_ALREADY_ACTIVE"; return NextResponse.json({ error: providerMissing ? "Add TAVILY_API_KEY to Vercel before running the scout." : alreadyRunning ? "A sourcing run is already active. Check again shortly." : "The sourcing run could not be completed." }, { status: providerMissing ? 503 : alreadyRunning ? 409 : 500 }); } }
export async function PATCH(request: Request) { try { await requireAscendWorkAdmin(); const parsed = patchSchema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: "Invalid scout update." }, { status: 400 }); if (parsed.data.action === "archiveLegacy") return NextResponse.json({ success: true, archived: await archiveLegacyScoutSignals() }); if (parsed.data.action === "promote") return NextResponse.json({ success: true, ...(await promoteScoutSignal({ signalId: parsed.data.id, contactName: parsed.data.contactName, contactEmail: parsed.data.contactEmail, contactRole: parsed.data.contactRole })) }); return NextResponse.json({ success: true, signal: await updateScoutSignal(parsed.data.id, parsed.data.status) }); } catch (error) { const message = error instanceof Error ? error.message : ""; console.error("ASCEND Partner Scout update error:", error); const validationError = message === "SCOUT_SIGNAL_NOT_VALIDATED"; const contactError = message === "SCOUT_CONTACT_NOT_OFFICIAL"; return NextResponse.json({ error: validationError ? "Only version-4 signals with a demonstrated need can be promoted." : contactError ? "Enter a real contact name and an email on the organisation’s official domain." : "The scout signal could not be updated." }, { status: validationError || contactError ? 409 : 500 }); } }
