import { auth } from "@clerk/nextjs/server";
import { redirect } from "next/navigation";
import { Award, CheckCircle2 } from "lucide-react";
import AppShell from "@/app/components/navigation/AppShell";
import SharePortfolio from "./SharePortfolio";
import { evidenceLabel } from "@/lib/projects/presentation";
import { listUserProjectEvidence } from "@/lib/projects/service";

export default async function ProjectEvidencePage(){const{userId}=await auth();if(!userId)redirect("/sign-in");const evidence=await listUserProjectEvidence(userId);return <AppShell><main className="min-h-screen bg-gradient-to-br from-[#020617] via-[#08111f] to-[#0f172a]"><div className="mx-auto max-w-6xl px-5 py-7 sm:px-6 sm:py-9"><p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-emerald-300">Projects</p><h1 className="mt-1 text-3xl font-bold text-white">My Portfolio</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">Work you complete through Projects becomes evidence you can return to and use responsibly.</p>{evidence.length?<div className="mt-6 grid gap-4 md:grid-cols-2">{evidence.map((item)=><article key={item.id} className="rounded-2xl border border-emerald-300/12 bg-emerald-300/[0.035] p-5"><div className="flex items-start justify-between gap-3"><CheckCircle2 className="text-emerald-300"/><span className="rounded-full bg-emerald-300/[0.08] px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[0.12em] text-emerald-200">{evidenceLabel(item.evidence_status,item.verified_by)}</span></div><h2 className="mt-4 text-lg font-semibold text-white">{item.title}</h2><p className="mt-2 text-sm leading-6 text-slate-400">{item.summary}</p><div className="mt-4 flex flex-wrap gap-2">{(item.skills as string[]).map((skill)=><span key={skill} className="rounded-lg bg-white/[0.05] px-2.5 py-1 text-xs text-slate-300">{skill}</span>)}</div><p className="mt-4 text-xs text-slate-500">Skills practised, not certified.</p><details className="mt-4 text-sm text-slate-300"><summary className="cursor-pointer">Preview what you would share</summary>{Object.entries(item.deliverable_preview as Record<string,string>).map(([title,text])=><div className="mt-3" key={title}><p className="font-semibold">{title}</p><p className="mt-1 whitespace-pre-wrap break-words text-xs leading-6">{text}</p></div>)}</details><SharePortfolio id={item.id} token={item.visibility === "shareable" ? item.share_token : null}/></article>)}</div>:<div className="mt-8 rounded-2xl border border-dashed border-white/10 p-10 text-center"><Award className="mx-auto text-slate-600"/><p className="mt-4 font-semibold text-white">Your evidence will appear here</p><p className="mt-2 text-sm text-slate-500">Finish a Project and reflect on your work to create your first private portfolio entry. Human review is a separate option.</p></div>}</div></main></AppShell>}
