import Link from "next/link";
import { auth } from "@clerk/nextjs/server";
import { redirect } from "next/navigation";
import { ArrowRight, FolderKanban } from "lucide-react";
import AppShell from "@/app/components/navigation/AppShell";
import { participationStatusLabel } from "@/lib/projects/presentation";
import { listUserParticipations } from "@/lib/projects/service";

export default async function MyProjectsPage(){const{userId}=await auth();if(!userId)redirect("/sign-in");const items=await listUserParticipations(userId);return <AppShell><main className="min-h-screen bg-gradient-to-br from-[#020617] via-[#08111f] to-[#0f172a]"><div className="mx-auto max-w-6xl px-5 py-7 sm:px-6 sm:py-9"><div className="flex items-end justify-between gap-4"><header><p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-cyan-300">Projects</p><h1 className="mt-1 text-3xl font-bold text-white">My Projects</h1><p className="mt-2 text-sm text-slate-400">Continue your work and follow every submission through review.</p></header><Link href="/projects" className="rounded-xl bg-cyan-500 px-4 py-2.5 text-sm font-bold text-slate-950">Find Projects</Link></div>{items.length?<div className="mt-6 grid gap-3">{items.map((item)=><Link key={item.id} href={`/projects/${item.project_id}/workspace`} className="group grid gap-4 rounded-2xl border border-white/[0.08] bg-white/[0.03] p-5 transition hover:border-cyan-300/20 sm:grid-cols-[1fr_auto] sm:items-center"><div><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-cyan-300/[0.08] px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[0.13em] text-cyan-200">{participationStatusLabel(item.status as never)}</span>{item.evidenceStatus&&<span className="rounded-full bg-emerald-300/[0.08] px-2.5 py-1 text-[10px] text-emerald-200">Evidence ready</span>}</div><h2 className="mt-3 text-lg font-semibold text-white">{(item.project as {title?:string}|null)?.title||"ASCEND Project"}</h2><p className="mt-1 text-sm text-slate-500">{(item.project as {summary?:string}|null)?.summary||"Open your workspace to continue."}</p></div><span className="flex items-center gap-2 text-sm font-semibold text-cyan-300">Open workspace <ArrowRight size={16} className="transition group-hover:translate-x-0.5"/></span></Link>)}</div>:<div className="mt-8 rounded-2xl border border-dashed border-white/10 p-10 text-center"><FolderKanban className="mx-auto text-slate-600"/><p className="mt-4 font-semibold text-white">You have not joined a Project yet</p><p className="mt-2 text-sm text-slate-500">Choose one clear piece of work and begin building proof.</p><Link href="/projects" className="mt-5 inline-flex rounded-xl bg-cyan-500 px-4 py-2.5 text-sm font-bold text-slate-950">Explore Projects</Link></div>}</div></main></AppShell>}
