begin;
-- A small independent learning collection. Drafts require admin review/publication.
-- Stable IDs avoid duplicate briefs. No sponsor endorsement or commercial use.
insert into public.ascend_projects(id,project_type,experience_kind,title,summary,brief,category,difficulty,skills,deliverables,estimated_minutes,feedback_level,ai_policy,ai_policy_detail,rights_model,usage_terms,submission_deadline,status,created_by)
values('aa202610-0200-4000-8000-000000000001','practice','explore','Explore a career through a small experiment','Compare two roles you are curious about, try one small task and decide what to explore next.','Choose two roles using public role descriptions. Compare their daily activities and entry expectations. Choose one safe, small task you can simulate yourself, such as outlining a research question or sketching a product improvement. Use public information only; do not contact employers or imply you worked for them. Explain how the experiment changes your direction.','Careers','beginner',array['Career research','Reflection'],array['Compare two roles and cite your public sources','Describe your small role experiment and what you produced','Explain which direction you want to explore next'],75,'individual','limited','Atlas can coach on your written work. You are responsible for accuracy, originality and acknowledging assistance.','portfolio','You retain ownership. ASCEND may process your work for feedback and your portfolio; commercial use requires separate permission.',now()+interval '365 days','draft','ascend-curated-library') on conflict(id) do nothing;
insert into public.ascend_project_criteria(project_id,title,description,weight,position) select 'aa202610-0200-4000-8000-000000000001','Clarity','The work responds clearly to the brief and includes each milestone.',40,1 where not exists(select 1 from public.ascend_project_criteria where project_id='aa202610-0200-4000-8000-000000000001' and position=1);
insert into public.ascend_project_criteria(project_id,title,description,weight,position) select 'aa202610-0200-4000-8000-000000000001','Reasoning','Choices and assumptions are explained with relevant support.',35,2 where not exists(select 1 from public.ascend_project_criteria where project_id='aa202610-0200-4000-8000-000000000001' and position=2);
insert into public.ascend_project_criteria(project_id,title,description,weight,position) select 'aa202610-0200-4000-8000-000000000001','Reflection','The participant identifies limitations and a useful next step.',25,3 where not exists(select 1 from public.ascend_project_criteria where project_id='aa202610-0200-4000-8000-000000000001' and position=3);
insert into public.ascend_projects(id,project_type,experience_kind,title,summary,brief,category,difficulty,skills,deliverables,estimated_minutes,feedback_level,ai_policy,ai_policy_detail,rights_model,usage_terms,submission_deadline,status,created_by)
values('aa202610-0200-4000-8000-000000000002','practice','build','Design a useful campus app','Create a small prototype that solves a student problem and explain your design choices.','Pick a familiar campus problem and define one user journey. Create three screens on paper or in a design tool, then walk through them with a fictional scenario. Include text descriptions so Atlas can comment without opening a file. Do not collect student personal data. This is an independent prototype, not work commissioned by your school.','Technology','beginner',array['Product thinking','UX design'],array['Describe the problem and a fictional user journey','Create three screens and explain the design choices','Walk through the prototype and propose one improvement'],180,'individual','limited','Atlas can coach on your written work. You are responsible for accuracy, originality and acknowledging assistance.','portfolio','You retain ownership. ASCEND may process your work for feedback and your portfolio; commercial use requires separate permission.',now()+interval '365 days','draft','ascend-curated-library') on conflict(id) do nothing;
insert into public.ascend_project_criteria(project_id,title,description,weight,position) select 'aa202610-0200-4000-8000-000000000002','Clarity','The work responds clearly to the brief and includes each milestone.',40,1 where not exists(select 1 from public.ascend_project_criteria where project_id='aa202610-0200-4000-8000-000000000002' and position=1);
insert into public.ascend_project_criteria(project_id,title,description,weight,position) select 'aa202610-0200-4000-8000-000000000002','Reasoning','Choices and assumptions are explained with relevant support.',35,2 where not exists(select 1 from public.ascend_project_criteria where project_id='aa202610-0200-4000-8000-000000000002' and position=2);
insert into public.ascend_project_criteria(project_id,title,description,weight,position) select 'aa202610-0200-4000-8000-000000000002','Reflection','The participant identifies limitations and a useful next step.',25,3 where not exists(select 1 from public.ascend_project_criteria where project_id='aa202610-0200-4000-8000-000000000002' and position=3);
insert into public.ascend_projects(id,project_type,experience_kind,title,summary,brief,category,difficulty,skills,deliverables,estimated_minutes,feedback_level,ai_policy,ai_policy_detail,rights_model,usage_terms,submission_deadline,status,created_by)
values('aa202610-0200-4000-8000-000000000003','practice','build','Build a fictional student business plan','Turn a small student business idea into a clear one-page plan supported by stated assumptions.','Choose a fictional student business. Describe the problem, likely customers, alternatives and a simple first experiment. Label every estimated number as an assumption and distinguish research from guesses. Do not approach customers or spend money for this project. Produce a plan someone can understand in five minutes.','Business','beginner',array['Market research','Business planning'],array['Define the audience, problem and alternatives','Write a one-page plan with explicit assumptions','Design a small future test and explain what would count as learning'],150,'individual','limited','Atlas can coach on your written work. You are responsible for accuracy, originality and acknowledging assistance.','portfolio','You retain ownership. ASCEND may process your work for feedback and your portfolio; commercial use requires separate permission.',now()+interval '365 days','draft','ascend-curated-library') on conflict(id) do nothing;
insert into public.ascend_project_criteria(project_id,title,description,weight,position) select 'aa202610-0200-4000-8000-000000000003','Clarity','The work responds clearly to the brief and includes each milestone.',40,1 where not exists(select 1 from public.ascend_project_criteria where project_id='aa202610-0200-4000-8000-000000000003' and position=1);
insert into public.ascend_project_criteria(project_id,title,description,weight,position) select 'aa202610-0200-4000-8000-000000000003','Reasoning','Choices and assumptions are explained with relevant support.',35,2 where not exists(select 1 from public.ascend_project_criteria where project_id='aa202610-0200-4000-8000-000000000003' and position=2);
insert into public.ascend_project_criteria(project_id,title,description,weight,position) select 'aa202610-0200-4000-8000-000000000003','Reflection','The participant identifies limitations and a useful next step.',25,3 where not exists(select 1 from public.ascend_project_criteria where project_id='aa202610-0200-4000-8000-000000000003' and position=3);
insert into public.ascend_projects(id,project_type,experience_kind,title,summary,brief,category,difficulty,skills,deliverables,estimated_minutes,feedback_level,ai_policy,ai_policy_detail,rights_model,usage_terms,submission_deadline,status,created_by)
values('aa202610-0200-4000-8000-000000000004','practice','build','Explain a fictional student budget','Build a clear budget using invented figures, test two scenarios and explain the trade-offs.','Use entirely fictional income and expenses to build a monthly student budget. Show calculations and assumptions. Explore how two changes affect the balance and write a plain-language explanation. This is a spreadsheet learning exercise, not personal financial advice. Never upload real bank statements or account numbers.','Finance','beginner',array['Spreadsheet modelling','Financial communication'],array['Create the fictional budget and show your calculations','Compare two scenarios with changed assumptions','Explain trade-offs, limitations and one useful improvement'],120,'individual','limited','Atlas can coach on your written work. You are responsible for accuracy, originality and acknowledging assistance.','portfolio','You retain ownership. ASCEND may process your work for feedback and your portfolio; commercial use requires separate permission.',now()+interval '365 days','draft','ascend-curated-library') on conflict(id) do nothing;
insert into public.ascend_project_criteria(project_id,title,description,weight,position) select 'aa202610-0200-4000-8000-000000000004','Clarity','The work responds clearly to the brief and includes each milestone.',40,1 where not exists(select 1 from public.ascend_project_criteria where project_id='aa202610-0200-4000-8000-000000000004' and position=1);
insert into public.ascend_project_criteria(project_id,title,description,weight,position) select 'aa202610-0200-4000-8000-000000000004','Reasoning','Choices and assumptions are explained with relevant support.',35,2 where not exists(select 1 from public.ascend_project_criteria where project_id='aa202610-0200-4000-8000-000000000004' and position=2);
insert into public.ascend_project_criteria(project_id,title,description,weight,position) select 'aa202610-0200-4000-8000-000000000004','Reflection','The participant identifies limitations and a useful next step.',25,3 where not exists(select 1 from public.ascend_project_criteria where project_id='aa202610-0200-4000-8000-000000000004' and position=3);
insert into public.ascend_projects(id,project_type,experience_kind,title,summary,brief,category,difficulty,skills,deliverables,estimated_minutes,feedback_level,ai_policy,ai_policy_detail,rights_model,usage_terms,submission_deadline,status,created_by)
values('aa202610-0200-4000-8000-000000000005','practice','build','Plan an original music release','Develop a sample release plan for your own music concept and create one original promotional asset.','Invent a release concept or use music you own. Define the audience and story, plan a two-week release calendar and draft an original promotional asset. Use no copyrighted material without permission. There is no promised label connection, distribution or promotion; this is a portfolio exercise you control.','Music','beginner',array['Creative strategy','Music communication'],array['Define the release concept, audience and story','Build a two-week calendar with realistic actions','Create one original asset and explain why it fits'],150,'individual','limited','Atlas can coach on your written work. You are responsible for accuracy, originality and acknowledging assistance.','portfolio','You retain ownership. ASCEND may process your work for feedback and your portfolio; commercial use requires separate permission.',now()+interval '365 days','draft','ascend-curated-library') on conflict(id) do nothing;
insert into public.ascend_project_criteria(project_id,title,description,weight,position) select 'aa202610-0200-4000-8000-000000000005','Clarity','The work responds clearly to the brief and includes each milestone.',40,1 where not exists(select 1 from public.ascend_project_criteria where project_id='aa202610-0200-4000-8000-000000000005' and position=1);
insert into public.ascend_project_criteria(project_id,title,description,weight,position) select 'aa202610-0200-4000-8000-000000000005','Reasoning','Choices and assumptions are explained with relevant support.',35,2 where not exists(select 1 from public.ascend_project_criteria where project_id='aa202610-0200-4000-8000-000000000005' and position=2);
insert into public.ascend_project_criteria(project_id,title,description,weight,position) select 'aa202610-0200-4000-8000-000000000005','Reflection','The participant identifies limitations and a useful next step.',25,3 where not exists(select 1 from public.ascend_project_criteria where project_id='aa202610-0200-4000-8000-000000000005' and position=3);
insert into public.ascend_projects(id,project_type,experience_kind,title,summary,brief,category,difficulty,skills,deliverables,estimated_minutes,feedback_level,ai_policy,ai_policy_detail,rights_model,usage_terms,submission_deadline,status,created_by)
values('aa202610-0200-4000-8000-000000000006','practice','build','Create a fashion concept case study','Create a small original fashion concept, explain your influences and document your design process.','Choose a fictional design brief and create three original sketches or written design descriptions. Explain influences with attribution, intended use, material assumptions and one iteration. Do not copy a brand collection or imply brand endorsement. Your deliverable is a case study, not a production order.','Fashion','beginner',array['Visual storytelling','Design research'],array['Define the audience, use case and attributed inspirations','Create three original concepts with written descriptions','Document a design revision and explain your final choice'],180,'individual','limited','Atlas can coach on your written work. You are responsible for accuracy, originality and acknowledging assistance.','portfolio','You retain ownership. ASCEND may process your work for feedback and your portfolio; commercial use requires separate permission.',now()+interval '365 days','draft','ascend-curated-library') on conflict(id) do nothing;
insert into public.ascend_project_criteria(project_id,title,description,weight,position) select 'aa202610-0200-4000-8000-000000000006','Clarity','The work responds clearly to the brief and includes each milestone.',40,1 where not exists(select 1 from public.ascend_project_criteria where project_id='aa202610-0200-4000-8000-000000000006' and position=1);
insert into public.ascend_project_criteria(project_id,title,description,weight,position) select 'aa202610-0200-4000-8000-000000000006','Reasoning','Choices and assumptions are explained with relevant support.',35,2 where not exists(select 1 from public.ascend_project_criteria where project_id='aa202610-0200-4000-8000-000000000006' and position=2);
insert into public.ascend_project_criteria(project_id,title,description,weight,position) select 'aa202610-0200-4000-8000-000000000006','Reflection','The participant identifies limitations and a useful next step.',25,3 where not exists(select 1 from public.ascend_project_criteria where project_id='aa202610-0200-4000-8000-000000000006' and position=3);
commit;
